### ISSUE TITLE
reason about not using NEE in Path Guiding

### ISSUE THREAD

**Issue by deadmarston** [Tom94/practical-path-guiding#10]
Dear Tom,

Hello. After checking your source code, I found that you didn't do NEE during the rendering, could you tell me the reason about not doing NEE?

Thanks.

**Comment by Tom94** [comment]
Hi there,

in the paper we refrained from using NEE to better stress test the different guiding algorithms. In any practical scenario you should absolutely use NEE---ideally a learning-based version, e.g. [Vévoda et al. [2018]](https://cgg.mff.cuni.cz/~jaroslav/papers/2018-bayesianlighting/index.htm).

That said, there are some fringe situations where direction-based path guiding actually learns better sampling distributions than NEE algorithms, especially, when the guiding algorithm is able to learn the product, which NEE typically disregards. We had this situation in a number of scenes with [Neural Importance Sampling [Müller et al. 2019]](https://tom94.net/data/publications/mueller18neural/mueller18neural-v4.pdf)... but never with PPG.

Cheers!

**Comment by deadmarston** [comment]
Hi

Thank you so much about the explaination.

Cheers!
