### ISSUE TITLE
Reason about setting new vertex with zero radiance

### ISSUE THREAD

**Issue by xh5a5n6k6** [Tom94/practical-path-guiding#12]
Hi Tom,

Thanks for your great work. 
In your code of evaluating direct light using BSDF sampling with MIS, you add a new vertex after recording radiance. I wonder why you set the new vertex with zero radiance when always doing NEE.

Thanks.

```
Spectrum L = throughput * value * weight;
if (!L.isZero()) {
    recordRadiance(L);
}

if ((!isDelta || m_bsdfSamplingFractionLoss != EBsdfSamplingFractionLoss::ENone) && dTree && nVertices < MAX_NUM_VERTICES && !m_isFinalIter) {
    if (1 / woPdf > 0) {
        vertices[nVertices] = Vertex{
            dTree,
            dTreeVoxelSize,
            ray,
            throughput,
            bsdfWeight * woPdf,
            (m_nee == EAlways) ? Spectrum{0.0f} : L,
            woPdf,
            bsdfPdf,
            dTreePdf,
            isDelta,
        };

        ++nVertices;
    }
}
```

**Comment by Tom94** [comment]
Hi Chia-Yu, NEE takes (relatively) good care of sampling _direct_ illumination, so when we do NEE, we only need PPG to learn how to sample _indirect_ illumination. Hence the omission of direct illumination in the path vertex.

Admittedly, in scenes with complicated occlusion and many light sources, Mitsuba's naïve NEE can get worse than what PPG is able to learn, so making PPG learn all illumination is sometimes a better choice.

**Comment by xh5a5n6k6** [comment]
Hi,

Thanks for your reply. :)
