### ISSUE TITLE
Questions about Sample Deposit

### ISSUE THREAD

**Issue by emilyT-CG** [Tom94/practical-path-guiding#16]
Hi Thomas,

Thank you for sharing the code! I'm a beginner in path guiding, so I'm a bit confused about some parts of the code:
1. When depositing samples into the quadtree, I noticed that you computed the Monte Carlo estimated irradiance as `Float irradiance = rec.radiance / rec.woPdf`. And I can see `woPdf` is defined as `woPdf = bsdfSamplingFraction * bsdfPdf + (1 - bsdfSamplingFraction) * dTreePdf`. So if I understand Monte Carlo theory correctly, this irradiance should be the estimated sum of _all the incoming directions_ (full sphere) right? And then it is recorded to the SDTree by `building.recordIrradiance()`. Currently I'm using the default `ENearest` mode, so I believe I ended up with calling the function `m_nodes[0].record(p, irradiance * statisticalWeight, m_nodes)`, which is defined as:
```
void record(Point2& p, Float irradiance, std::vector<QuadTreeNode>& nodes) {
        SAssert(p.x >= 0 && p.x <= 1 && p.y >= 0 && p.y <= 1);
        int index = childIndex(p);

        if (isLeaf(index)) {
            addToAtomicFloat(m_sum[index], irradiance);
        } else {
            nodes[child(index)].record(p, irradiance, nodes);
        }
    }
```
So why is the estimated irradiance of all incoming directions deposited into a leaf node in the quadtree? From my understanding, each quad in the quadtree needs to store the irradiance of the solid angle corresponding to that quad. For example, a bigger quad should have a larger irradiance than a smaller quad.

2. I also found a `statisticalWeight` variable in the code, and I don't know what it represents. I printed its value and looks like it is either `1.0` or `0.5`.

I definitely missed some important details in your code since I'm new to this field. It would be great if you can clarify these. Thanks a lot!

Thanks,
Emily

**Comment by emilyT-CG** [comment]
I have figured it out.

**Comment by Tom94** [comment]
Glad to hear! Apologies for not answering sooner, I was out on vacation until today.
