### ISSUE TITLE
Question regarding statisticWeights in building quadtree

### ISSUE THREAD

**Issue by deadmarston** [Tom94/practical-path-guiding#17]
Hello Tom,

Thank you for your great work.
I hold a question regarding the your quadtree resetting part. In your quadtree reset function, you will refine both the building quadtree and sampling quadtree and then reset the building quadtree to zero if I understand it correctly. I wonder why you didn't reset the statisticWeights to zero in building quadtree as well (while I don't think it affect performance a lot)?

Thanks for your help:)

Cheers

**Comment by Tom94** [comment]
Hi there, the `m_atomic.statisticalWeight` is set to zero in the first line of `DTree::reset` via the `m_atomic = Atomic{};` statement.

I have to admit that this code is super convoluted. Apologies for that. It took me a while to find the right place, which for a moment made me worry I'd overlooked a serious bug in the implementation. :p

Cheers!

**Comment by deadmarston** [comment]
Hi Tom,

Thanks for your reply. 
Yeah, I found it. I am sorry that I overlook there. :)

Cheers!
