### ISSUE TITLE
About Vorba's guided path tracer

### ISSUE THREAD

**Issue by ShilinC** [Tom94/practical-path-guiding#7]
Hi Tom,

Thanks for sharing the great work! I found that in your scene XML files, you have the commented out parameters for Vorba's guided path tracer. Did you implement one on your own or use their releasing code? Since I use Linux, Vorba's original code cannot be directly compiled on my computer and looks like many things need to be modified to make it work on Linux, for example, their LibImportance library (maybe I'm wrong). Do you have Vorba's work integrated into your framework that could be run on Linux? Thanks!

Best,
Shilin

**Comment by Tom94** [comment]
Hi Shilin,

unfortunately, we don't have a Linux implementation of Vorba et al.'s guided path tracer. We ran a locally modified version of their implementation on Windows.

The modifications were to
- make it work with all of our scenes, to
- make it include direct illumination (by default, it guides indirect illumination and relies on shadow rays for direct illumination), and to
- make it scale to larger numbers of threads.

Cheers,
Thomas

**Comment by ShilinC** [comment]
Thanks!
