### ISSUE TITLE
Scons build errors

### ISSUE THREAD

**Issue by zheng95z** [Tom94/practical-path-guiding#8]
Dear Tom:

Hi!

I cloned the code & dependencies from you, but when I build via Scons, some errors occured:

`src\libpython\core.cpp(2244) : error C2780: 'boost::python::class_<mitsuba::AABB1,boost::python::detail::not_specified,boost::python::detail::not_specified,boost::python::detail::not_specified> &boost::python::class_<mitsuba::AABB1,boost::python::detail::not_specified,boost::python::detail::not_specified,boost::python::detail::not_specified>::def(const char *,Fn,const A1 &,const A2 &,const A3 &)' : expects 5 arguments - 2 provided 
dependencies\include\boost/python/class.hpp(266) : see declaration of 'boost::python::class_<mitsuba::AABB1,boost::python::detail::not_specified,boost::python::detail::not_specified,boost::python::detail::not_specified>::def'`

But I can build the original Mitsuba 0.5.0 successfully.
Any clues?

Windows10
VS2013
Python 2.7.15

Big thanks.

**Comment by Tom94** [comment]
Hi there, unfortunately I don't see any obvious problem.

If you don't need the python bindings, you could try commenting out the python-relevant lines in config-win64-msvc2013.py such that mitsuba is built without python support.

**Comment by zheng95z** [comment]
> Hi there, unfortunately I don't see any obvious problem.
> 
> If you don't need the python bindings, you could try commenting out the python-relevant lines in config-win64-msvc2013.py such that mitsuba is built without python support.

Thanks! It works.

**Comment by Tom94** [comment]
Glad to hear. :)
